export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
import { Box } from "@chakra-ui/react"
//apenas login recebe as edições feitas aqui
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div suppressHydrationWarning >
            <Box display="flex" h="100vh" w="100%">
                <Box
                    w="260px"
                    bg="gray.800"
                    color="white"
                    p={6}
                    position="relative"      
                    boxShadow="lg"
                >
                    <h1 style={{ fontWeight: "bold", fontSize: "22px" }}>Easy Food</h1>
                    <p style={{ marginTop: "20px" }}>
                        Sidebar fixa sem animação.
                    </p>
                </Box>
                <Box flex="1" p={6} bg="gray.50">
                    {children}
                </Box>
            </Box>
        </div>
    )
}